### ISSUE TITLE
Shell scripting tutorials

### ISSUE THREAD

**Issue by Tokazama** [CognitiveNeuroLab/CNL_index#2]
Should we provide a link to a common she'll scripting tutorial that people should go through? I know it's not a part of the pipelines presented here but it's pretty much impossible to teach neuroimaging stuff to people unless they can get around in a terminal.

**Comment by DouweHorsthuis** [comment]
Great plan! feel free to add it.

**Comment by kevinprinsloo** [comment]
Good point, we were planning on adding some jupyter notebooks alongside the pipelines, it's just a matter of spending some time to code it up. Also, if you have any good resources for us newbs on how to implement what you suggested that would be handy as well.

**Comment by Tokazama** [comment]
I'll look around a bit. I use to have some go to material when I was teaching this stuff six years ago, but who knows if the links are still valid or there is something better now. I'm assuming that unix based scripting is sufficient for now given that most neuroimaging software is designed around mac or linux systems.
